server:
  port: 8090
  servlet:
    context-path: /api

spring:
  application-name: "Gestion des taches"
  datasource:
    url: jdbc:mariadb://localhost:3306/gestion_taches
    username: admin
    password: Ktoto1956
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: "org.hibernate.dialect.MariaDBDialect"
    hibernate:
      ddl-auto: "update"
